spring.datasource.url=jdbc:mysql://db:3306/mercalist_db
spring.datasource.username=root
spring.datasource.password=${DB_PASS:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
